# Generated by Django 3.2.25 on 2025-11-30 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20251129_1005'),
    ]

    operations = [
    ]
