# Generated by Django 3.2.25 on 2025-11-29 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0003_auto_20251129_1005'),
        ('managers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manager',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='manager',
            name='bio',
            field=models.TextField(blank=True, help_text='Manager biography'),
        ),
        migrations.AddField(
            model_name='manager',
            name='department',
            field=models.CharField(blank=True, help_text='Department', max_length=100),
        ),
        migrations.AddField(
            model_name='manager',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the manager is active'),
        ),
        migrations.AddField(
            model_name='manager',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='phone',
            field=models.CharField(blank=True, help_text='Manager phone number', max_length=30),
        ),
        migrations.AddField(
            model_name='manager',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('hr', 'HR Manager'), ('project_manager', 'Project Manager'), ('team_lead', 'Team Lead'), ('executive', 'Executive')], default='admin', help_text='Manager role', max_length=50),
        ),
        migrations.AddField(
            model_name='manager',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='company.company'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='manager',
            index=models.Index(fields=['company', 'is_active'], name='managers_ma_company_a18843_idx'),
        ),
        migrations.AddIndex(
            model_name='manager',
            index=models.Index(fields=['user'], name='managers_ma_user_id_8febad_idx'),
        ),
        migrations.AddIndex(
            model_name='manager',
            index=models.Index(fields=['role'], name='managers_ma_role_99d873_idx'),
        ),
    ]
