# Generated by Django 3.2.25 on 2025-11-29 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20251129_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(max_length=50)),
                ('confidence', models.FloatField(default=0.0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='emotions/')),
                ('context', models.CharField(default='login', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_data', to='employees.employee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='emotiondata',
            index=models.Index(fields=['employee', 'created_at'], name='employees_e_employe_eb6a0e_idx'),
        ),
        migrations.AddIndex(
            model_name='emotiondata',
            index=models.Index(fields=['emotion'], name='employees_e_emotion_9173b6_idx'),
        ),
        migrations.AddIndex(
            model_name='emotiondata',
            index=models.Index(fields=['context'], name='employees_e_context_91f55d_idx'),
        ),
    ]
